### PR TITLE
Finalize new term request for material entities top-level term

### PR DESCRIPTION
**Pull request by cboelling**
Following the task group's discussion and recommendation from January 18 I created a draft new term request (NTR) using the NTR template in the task group's repository. The draft builds on [the previous discussion in the task group](https://github.com/tdwg/material-sample/issues/31) and [the previous proposal to import dcterms:PhysicalResource ](https://github.com/tdwg/dwc/issues/421#)to implement the top-level term.
 
Significant parts of the draft NTR have been taken from the previous term request submitted by @baskaufs. I took the liberty of re-using parts of it as many aspects of the two proposals are identical - they differ in how the top-level term is implemented, not in its intended role.
 
The stability justification makes reference to `dwc:MaterialSample`, `dwc:PreservedSpecimen`, `dwc:LivingSpecimen`, `dwc:FossilSpecimen` as existing terms in DwC which would informally be regarded as subclasses of the new term. While I think that what is contained in this section is correct, I wonder if information should be added regarding the addition of `dwc:materialEntityType` with an extensible list of corresponding values and if this means that the other terms need to be deprecated after all (I don't think they should - my understanding is that schema information (subclasses etc) and possibly other semantic information is easiest to complement the base terminology as additional layers if all relevant terms are actually included as individual elements in the terminology). Please advise.
 
Please also review the usage notes and the examples in particular. I know that the placement of `dwc:Organism` is contentious. The current examples reflect my understanding of the new term.

### CODE REVIEW

**Comment by tucotuco** [comment]
This is great. I have some suggested edits. I can do that as comments here, or commit the suggestion on that branch or wait until it gets merged. Do you have a preference?

**Comment by cboelling** [comment]
> This is great. I have some suggested edits. I can do that as comments here, or commit the suggestion on that branch or wait until it gets merged. Do you have a preference?

For specific edits, especially uncontroversial ones, I would suggest to directly add one or several commits to this feature branch. 

If you think the edits would be conceptual in nature, changing existing parts of the draft significantly with potential controversy - then perhaps let's first discuss those not to lose oversight.

A third option would be to comment individual lines / blocks in a specific commit (i.e. incrementally changed version of the file) which is also fine.

**Comment by baskaufs** [comment]
I like all of this except that I think the first sentence of the Usage Comments 

> The term is expected to be used to refer to material entities, i.e., entities that consist in part or whole of physical matter. 

is redundant. It basically repeats the label and then repeats part of the definition. If it is important to say that the class refers to "material entities", then I would suggest that be put in the definition as: "A material entity that is expected..." Otherwise, nothing would be lost by deleting that first sentence.

**Comment by cboelling** [comment]
The current draft for the term request for `dwc:MaterialEntity` including all incremental contributions ("commits") is _always_ visible for inspection at this URL: https://github.com/tdwg/material-sample/blob/ntr-material-entity/primary_deliverable/materialentity.md

Thank you for the contributions so far - these go nicely together in my view. Please add any further comments regarding the proposal for the New Term Request for `dwc:MaterialEntity` until tomorrow 1pm UTC either here or in [the original discussion thread in the task group's repo](https://github.com/tdwg/material-sample/issues/31). Unless something controversial comes up, I will then pull the draft into the canonical version of this Task Group's repo. I also understand that the consensus view is to then use the draft and formulate an NTR in Dwc's main repo, which I offer to do right after merging. If you prefer a different course of action, please come forward and let us know also by tomorrow 1pm UTC.

**Pull request merged**
